language: python
python:
- '3.6'
branches:
  only: feature/test
install:
- pip install awscli
- pip install aws-sam-cli
script:
- sam validate --region ap-southeast-2
- sam package --template-file template.yml --s3-bucket serge-test-23032022 --output-template-file packaged.yaml --region ap-southeast-2
deploy:
  provider: script
  script: sam deploy --template-file packaged.yaml --stack-name serge-serverless-test
  skip_cleanup: true
  on:
    branch: feature/test
notifications:
  email:
    on_failure: always
  global:
  - AWS_DEFAULT_REGION=ap-southeast-2
env:
  global:
  - secure: P6qDb47XOxwlfcK8SL99xvjxWCASERkxaYZe5/C6/MyOKxAc9k72yqcwitVEJ6VbJJP3LdMHwF1DEeRB5D9DzbfKbw9GNA70o2rEY16ZQPVZgftRvuPksN3yhOYvVLlUZLNCb1PRNmNxaGY2Ym9/ttkhcOoAKnwKpYQSRuE+uGpngbQ68qq7bP1gSPuhkPt2A/Z8GbUDruR7Jj6Asdf2ysihOpGsJczcsEBsp446DA80Aqrzc6uRIH0cIZpFXxeO6EN72rWeSZeQXV7I+1kpSvDZhco3YCdaUR/bysxDAtI+RKcAe0CjCsHIY6UWEMktDMXYPDDCyIdp5hgj823nRAsnTqG1wZU33Ca1+3VbHK28zrTLK63ohYVqz9mJcHXOa8HXsN487U1v3SDvZ44umVTm82+vO1tkYaFoJOgITXEz2dVQW8uTcx2k+bLaNITZWDUHWJ/e1LI1yHIpg4FJ3ns+dCsWQ3/qp/lQ3Rq1NCgJafn2cyYN/KRAlMur/KCi5ApnX4JmBWKSyWcTsQIIO6qEPrC0aIXbPQ2aEGXV49N511wIhyplau2Ko4GKMVKEAQfFyK4aNzdxTtoGViEb3KiwLfZQrRFW88x/5VgKb/VhMNFawWPs7x9A2fdSoms2/ase7Sqs/4TOjD8RqmTnmsSGnXQp9hQo/M6q739KL4c=
  - secure: n7beddD5h0WfgSvSt+Yw9pP+v50S2YItRVVH13omhoL1YOUAe9678kVnDS07kWCqgAZTDk9fZTIQrSnzQFAXXSskrx1OtA/WH1r9GfE/xxtxzWl/s79kh1/hpVPSfd4l03fTfeBcku8SDueBZF4P7vvesfWkXASgA2Px43sBKcSdypImMgMcn913DY5cHDUA5oU/js5LDv3RyAWiX7UClXJaPhTPDbvk5nGSClpMusMyBY81nT2K5J6TKhLtUqOzsThIanna8i0lm+kCX9CjaiJg+FlcsOtfhD5xDRRRNVQfNv9cuZtP9y1FbQCuFyjX6rndlQ3LOdrc385Aw2vWTcfL8ZjBGFQ7n+NvbntsNpx+5LP+M8uTCRg1j2eOqroK3OFs8T1AskUWIWaSv03CwwiZUFVyUCiXxANowNAXpRAuMoE+JuIWk88Lmm1a1PxY67dI9yoYfkb2JauiZjY4Ael3OT8ZCk5ugjY/Dn0+K7iGA2nZjrj2adOI7lyaDm4nDhNLGL0YTzTDcqO7F7L4THx6EEvH4mRPa9GLqFA00q3V3jxtH/UsCic/qwW3zAIwl4T07rpIHtNeTZmRTv/XfCzdE+F+Bp3bAfhoAeqoxM2m2t6BQUxxaWuBOwa7JJ5pZVxM9t0cGCOLJlALuZlH3Dy2rEUy5CJYm7kyhIuVNbc=
