language: python
python:
- '3.6'
branches:
  only: feature/test
install:
- pip install awscli
- pip install aws-sam-cli
script:
- sam validate
- sam package --template-file template.yaml --s3-bucket serge-test-23032022 --output-template-file
  packaged.yaml
deploy:
  provider: script
  script: sam deploy --template-file packaged.yaml --stack-name serge-serverless-test
  skip_cleanup: true
  on:
    branch: feature/test
notifications:
  email:
    on_failure: always
  global:
  - AWS_DEFAULT_REGION=ap-southeast-2
env:
  global:
  - secure: fO7NnzA2vnTGvCqWCnsAiUIejFklS8IFpevyPAGyyyuCa6ZFKKAR66obsUE32OtYlvRwRDkTo9A5UHiYMTNGZKur55xX+pIVafRuygF+kZXZl1UlWjMBoT0O9WPhRKBxWiMDYwkh7EWHRtb2Pg0zzj4QX6YPPl1c30NQd0Ww12BX3Mh9u853LgP2deQz9QXJ3DU80Fhex6m1ERc5dqpzMXJJ1WnzqRMIcBa0CWnLY3TJITme4ulAEpy+0An2C64f5N5kAeGOzVzuxgDFLqY5zhmpH9uNHqvwYWQDyWyMwGUXDPps/OyU5cP8dKb7dJMl375rMfXLyUDK/V80PKz9CYSiYGlJ3W2jMTu4p0Vb7VbiQD9OH6PdVWkC5eLS7Mml+IqGng70p/9UkTY/rHdbi8E5A1d+RLJuDPg+kSgDCdCsg4cYNwhXshhcd+OBJazbeizMmgazstBIog2yx/usY2W6mBcVz739/U2TiKbfVDhEMsRHYr7VrPG7wAgMS8Osw2B935jrG2E27qJJr6zY+nxjfIY4edlMIl8uIs1BnVpkkelx32weCC25AWHCNuOKoQ0dJk17+39ZUpT/nX3fdKYdcASv/AZLfEw2RvP5k2ADv5gfrCgDIsDs6A83EWGP5OjnkLimCOLXFNR8sl+rGCfIEUerYaD4c10YZiohwtk=
  - secure: bQHu1a0V15NJa4Q8y1xdtf8d8u4k2HdedsQS5AJr05kTlEp1r3gnu52xTIkyWyCSNMRi5hftQU5J04pZKLgix+5oCsFZVfV4re3iTqpOQNEq9DE/RlUHHtjxYzmY3Q8D2DVcNuubfkGNvSnxNaXpNmWPo1j76rW2olOl4BXqylw5cW04roHi1tiS22uZP0FUJ5nb2PAMhqOEEuaWhktkWe+Nu+m1WOJXblvvEVgCgNlv0kMN7YHCiNSQu8hPN00zugQgwEhXQ1qSwd+WfGj2i5ZFPfZJbSq5vw32CflZuUOFZWiugjPWc8i7FeK/pq5dilappui92nwzJQ5z7Y1nOvcutofxyb3Lp/J4Ba9M/P6q0M9nxdU7SsC5T6p34W+xVNFnqNbonLfDcJHzJGSl8i0bq5ZiP22n+r7d4v2hF983MD2qImMLmYMEIg2yGux6Ni2sv6P05Ox1qBOX/W/mj2G2T1zVTlalfbBa5BdcV1wT0itcSuTxc7HbxFQOZ8UffbNpwoQs5MgA+6KWdrrK2aK8idlyO9fYaJCm00Uhn6w6YAjrA2638WEX/Orp6sndQYxuaqVfAl7OPRdxmDjFrnQSQtRCepE1mcY3yo9kngq+AveFSfP8/6colebWk27Qzk5pWVqt3d5qPpWZbZduKLLsYmkfcZsn7qeCkrivb6s=
